version: '3.8'

services:
  web:
    image: fedxl/storage:shipkz
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn shipkz.wsgi:application --bind 0.0.0.0:8000 & 
             daphne -b 0.0.0.0 -p 8001 shipkz.asgi:application"
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    expose:
      - "8000"
      - "8001"
    depends_on:
      - db
      - redis
  db:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_DB: master_base
      POSTGRES_USER: master_admin
      POSTGRES_PASSWORD: 54321

  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:9933:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - web
  redis:
    image: redis:latest
    expose:
      - "6379"
  celery:
    image: fedxl/storage:shipkz

    command: celery -A shipkz worker --loglevel=info
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - redis
      - web
  celery-beat:
    image: fedxl/storage:shipkz

    command: celery -A shipkz beat --loglevel=info
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - redis
      - web
volumes:
  static_volume:
  media_volume:
  postgres_data:
