version: '3.8'

services:
  web:
    build: .
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    ports:
      - "127.0.0.1:80:8000"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  static_volume:
  media_volume:
  postgres_data:
