"""Your migration message here

Revision ID: 97be5691c39a
Revises: 
Create Date: 2023-10-10 11:31:27.978011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97be5691c39a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_users', sa.Column('web_usernane', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'web_users', ['web_usernane'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_users', type_='unique')
    op.drop_column('web_users', 'web_usernane')
    # ### end Alembic commands ###
