"""firs

Revision ID: be60a74b04a4
Revises: 47a7036b3c7c
Create Date: 2023-10-10 07:02:26.218433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be60a74b04a4'
down_revision: Union[str, None] = '47a7036b3c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_users', sa.Column('web_username', sa.String(), nullable=True))
    op.drop_constraint('web_users_web_usernane_key', 'web_users', type_='unique')
    op.create_unique_constraint(None, 'web_users', ['web_username'])
    op.drop_column('web_users', 'web_usernane')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_users', sa.Column('web_usernane', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'web_users', type_='unique')
    op.create_unique_constraint('web_users_web_usernane_key', 'web_users', ['web_usernane'])
    op.drop_column('web_users', 'web_username')
    # ### end Alembic commands ###
