"""Your migration message here

Revision ID: fd5fc8e58274
Revises: 97be5691c39a
Create Date: 2023-10-10 13:01:55.070493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5fc8e58274'
down_revision: Union[str, None] = '97be5691c39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_users', sa.Column('web_username', sa.String(), nullable=True))
    op.drop_constraint('web_users_web_usernane_key', 'web_users', type_='unique')
    op.create_unique_constraint(None, 'web_users', ['web_username'])
    op.drop_column('web_users', 'web_usernane')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_users', sa.Column('web_usernane', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'web_users', type_='unique')
    op.create_unique_constraint('web_users_web_usernane_key', 'web_users', ['web_usernane'])
    op.drop_column('web_users', 'web_username')
    # ### end Alembic commands ###
