"""empty message

Revision ID: 03cf90a54b42
Revises: 
Create Date: 2023-10-29 22:03:31.147040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cf90a54b42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('is_forward', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.DateTime(), nullable=False),
    sa.Column('arrived_to_forward', sa.DateTime(), nullable=False),
    sa.Column('got_track', sa.DateTime(), nullable=False),
    sa.Column('arrived_to_kz', sa.DateTime(), nullable=False),
    sa.Column('received_in_kz', sa.DateTime(), nullable=False),
    sa.Column('send_to_RU', sa.DateTime(), nullable=False),
    sa.Column('success', sa.DateTime(), nullable=False),
    sa.Column('relative_price', sa.String(), nullable=False),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('store_order_number', sa.String(), nullable=True),
    sa.Column('trek', sa.String(), nullable=False),
    sa.Column('cdek', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('exchange', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('order_status_info')
    # ### end Alembic commands ###
