"""empty message

Revision ID: 25577d3ba58c
Revises: 03cf90a54b42
Create Date: 2023-10-29 22:20:16.331772

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25577d3ba58c'
down_revision: Union[str, None] = '03cf90a54b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_message', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'messages', ['message_id'], ['id'])
    op.alter_column('managers', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('managers_user_id_key', 'managers', type_='unique')
    op.create_unique_constraint(None, 'managers', ['short_name'])
    op.create_unique_constraint(None, 'managers', ['key'])
    op.drop_constraint('fk_storage', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['storage_id'], ['user_id'])
    op.drop_constraint('order_status_manager_id_fkey', 'order_status', type_='foreignkey')
    op.drop_constraint('orders_buyer_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('fk_message', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'messages', ['message_id'], ['id'])
    op.drop_constraint('users_main_user_fkey', 'users', type_='foreignkey')
    op.create_unique_constraint(None, 'users_app', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_app', type_='unique')
    op.create_foreign_key('users_main_user_fkey', 'users', 'user_main', ['main_user'], ['id'])
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('fk_message', 'photos', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('orders_buyer_fkey', 'orders', 'buyers', ['buyer'], ['id'])
    op.create_foreign_key('order_status_manager_id_fkey', 'order_status', 'managers', ['manager_id'], ['user_id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('fk_storage', 'messages', 'users', ['storage_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'managers', type_='unique')
    op.drop_constraint(None, 'managers', type_='unique')
    op.create_unique_constraint('managers_user_id_key', 'managers', ['user_id'])
    op.alter_column('managers', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('fk_message', 'documents', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
